### ISSUE TITLE
URI that was provided is invalid

### ISSUE THREAD

**Issue by spacem** [sachbalag/ibm-maximo-api#9]
When I fetch with the api it creates this path:
/maximo/oslc//os/REP_ASSET?lean=1&oslc.select=assetnum%2Cdescription%2Clocation%2Cstatus&oslc.pageSize=11

Notice the double slash oslc//os

Not sure why but this causes the error:
message=BMXAA8816E - The URI context  is not supported as the URI that was provided is invalid., statusCode=400, reasonCode=BMXAA8816E

Looking in resources/resourceset.js I see this code on lines 42 & 43 which I believe is causing the double slash.

X_PUB_PATH = maxfactory.auth_scheme + '/oslc/';
REST_PATH = X_PUB_PATH + '/os/';

Is there some way I can work around this? Any chance of a fix sometime? Is this library still maintained?

**Comment by apbram** [comment]
Hi,
I had the same issue and when I'm running locally I could fix it by removing the extra "/" before "os":
// Constructor 2
    if(maxfactory != "undefined" && mbo != "undefined")
    {
        X_PUB_PATH = maxfactory.auth_scheme + '/oslc/';
        **REST_PATH = X_PUB_PATH + 'os/';**

However, when I run the API in Bluemix I don't have access to node_modules. It would be great if it is fixed in the source and provided as a new node_module version.

**Comment by sachbalag** [comment]
Merged Ana's fix and published to NPM.
